services:
  mongo:
    image: mongo:4.4  # MongoDB v4.4 chosen for better CPU compatibility (no AVX requirement)
    container_name: mongo_${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    container_name: backend_${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:4000"
    environment:
      - NODE_ENV=production
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    container_name: nextjs_${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    ports:
      - "${NEXT_PUBLIC_PORT}:3000"
    environment:
      - NODE_ENV=production
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

# Shared network for all services
networks:
  appnet:

# Persistent MongoDB volume
volumes:
  mongo_data:
